#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
require "#{RAILS_ROOT}/config/environment"
require 'rails_generator'
require 'rails_generator/scripts/generate'

class Rails::Generator::Base
  def self.use_application_sources!
    reset_sources
    sources << Rails::Generator::PathSource.new(:builtin, "#{RADIANT_ROOT}/lib/generators")
    plugins_path = File.expand_path(File.join(RAILS_ROOT, %w(vendor plugins)))
    sources << Rails::Generator::PathSource.new(:"plugins (vendor/plugins)", "#{plugins_path}/*/**/{,rails_}generators")
  end
end

Rails::Generator::Base.use_application_sources!

require 'commands/generate'
